version: 0.2

phases: 
  install:
    commands:
    # Install Node
    - echo Installing Node...
    - curl -sL https://deb.nodesource.com/setup_16.x | bash -
    - apt install -y nodejs

    # insta Yarn
    - echo Installing Yarn...
    - npm install --global yarn
  pre_build:
    commands:
      # install depencies
      - echo Installing dependencies...
      - yarn


  build:
    commands: 
      # tests
      - echo Testing...
      - yarn test --watchAll=false
      # build
      - echo Building...
      - yarn build
      #- echo $CODEBUILD_SRC_DIR

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build