version: 0.2

phases: 
  install:
    commands:
    # Install Node
    - echo Installing Node...
    #- curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    #- . ~/.nvm/nvm.sh
    #- nvm install node
    - curl -sL https://deb.nodesource.com/setup_16.x | -E bash -
    - apt install -y nodejs

    # insta Yarn
    - echo Installing Yarn...
    - npm install --global yarn
  pre_build:
    commands:
      # install depencies
      - echo Installing dependencies...
      - yarn


  build:
    commands: 
      # tests
      - echo Testing...
      - yarn test
      # build
      - echo Building...
      - yarn build
      #- echo $(ls $CODEBUILD_SRC_DIR)

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build